# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the `springboot-app-server` directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 4000 on the container to port 4000 on the host machine
    restart: always
    depends_on:
      - db # This service depends on mysql. Start that first.
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://youtube-crawler_db_1:3306/remote_api_manager?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kayak
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Database Service
  db:
    image: mariadb:10.5.8
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: remote_api_manager
      MYSQL_USER: root
      MYSQL_PASSWORD: kayak
      MYSQL_ROOT_PASSWORD: kayak
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

# YouTube Download Service
  download:
    image: seventhnode/youtubedlserver
    ports:
      - "8081:8081"
    volumes:
      - download-data:/youtube-dl
    networks:
      - download
  client:
    image: seventhnode/youtubedataclient
    ports:
      - "4200:4200"
    networks:
      - frontend

# Volumes
volumes:
  db-data:
  download-data:

# Networks to be created to facilitate communication between containers
networks:
  backend:
  download:
  frontend: